# Display the coverage of the tests
# with gcovr
name: Coverage



# Run on every push and pull request
on: [push, pull_request]



# Run the tests and upload the coverage
jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run tests
        run: make tests_run

      - name: Coverage
        run: |
          gcovr --exclude tests/ --xml -o coverage.xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md